### ISSUE TITLE
Clusterlink custom NIC support

### ISSUE THREAD

**Issue by wangyizhi1** [kosmos-io/kosmos#302]
**Why is this needed**:

Currently, ClusterLink's support for custom network cards is not comprehensive enough. When creating a VXLAN network card, it utilizes clusterNode.spec.ip, which is obtained by the controller-manager from node.status.addresses.InternalIP. If there is a need to use a different network card than the one corresponding to nodeIP, this can lead to issues.

**What would you like to be added**:

Addressing this issue requires modifications to several components:

- [x] 1. The agent should retrieve the corresponding IP address based on `clusternode.spec.interfaceName` and update `clusternode.spec.ip` and `clusternode.spec.ip6` accordingly. #299 #303 
- [ ] 2. The controller-manager should eliminate modifications to `clusternode.spec.ip` and `clusternode.spec.ip6`.
- [ ] 3. The network-manager needs to be compatible with the short-term absence of values in `clusternode.spec.ip` and `clusternode.spec.ip6`, and recalculate nodeConfigs after they are set.  #301

**Comment by wangyizhi1** [comment]
- [ ] The network-manager needs to be compatible with the short-term absence of values in clusternode.spec.ip and clusternode.spec.ip6, and recalculate nodeConfigs after they are set. #301

**Comment by OrangeBao** [comment]
- [ ] [The agent should retrieve the corresponding IP address based on clusternode.spec.interfaceName and update clusternode.spec.ip and clusternode.spec.ip6 accordingly.](https://github.com/kosmos-io/kosmos/pull/299)
